require 'rubygems'
require 'pry'

# require 'simplecov'
# SimpleCov.start 'rails' do
#   merge_timeout 3600
# end

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'

# Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# order to ease the transition to Capybara we set the default here. If you'd
# prefer to use XPath just remove this line and adjust any selectors in your
# steps to use the XPath syntax.
Capybara.default_selector = :css

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how 
# your application behaves in the production environment, where an error page will 
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.

our_default_strategy = :transaction

begin
  DatabaseCleaner.strategy = our_default_strategy
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

DatabaseCleaner.clean_with :truncation

Before do
  DatabaseCleaner.start
end

After do |scenario|
  DatabaseCleaner.clean
end

###############################
# TODO capture only on demand (test profile?)
TRACE_DIR = File.join(Rails.root, "app")
@@captures = []
class Model
  include RCapture::Interceptable
  capture :methods => [:availability_in] do |c|
    #@@captures << [["#{c.sender.class}##{c.method}"] + caller.select {|x| x.include? TRACE_DIR}, c] 
    @@captures << ["#{c.sender.class}##{c.method}"] + caller.select {|x| x.include? TRACE_DIR} 
  end
end
at_exit do
  g = GraphViz.new( :G, :type => :digraph )
  #@@captures.map(&:first).uniq.each do |trace|
  @@captures.uniq.each do |trace|
    nodes = trace.map do |t|
      g.add_nodes( t.gsub(TRACE_DIR, ''), :shape => "box" )
=begin
      tt = t.gsub(TRACE_DIR, '').split(':', 2)
      if tt.size > 1
        sg = g.add_graph(tt.first, :label => tt.first)
        sg.add_nodes( tt.last, :shape => "box" )
      else
        g.add_nodes( tt.last, :shape => "box" )
      end
=end
    end
    nodes.each_cons(2) do |node|
      g.add_edges( node[1], node[0] )
    end
  end
  `mkdir -p doc/diagrams/generated`
  g.output( :dot => "doc/diagrams/generated/captures.dot" )
end
