include:
  - cider-ci/jobs/good-to-merge.yml
  - cider-ci/jobs/deploy-to-zhdk-leihs-prod.yml
  - cider-ci/jobs/deploy-to-zhdk-leihs-staging.yml
  - cider-ci/jobs/deploy-to-zhdk-leihs-test.yml
  - cider-ci/jobs/deploy-to-zhdk-leihs-demo.yml
  - cider-ci/jobs/deploy-to-zhdk-dev-servers.yml
  - cider-ci/jobs/deploy-to-ffzh-leihs-staging.yml
  - cider-ci/jobs/import-v3-to-v4.yml
  - cider-ci/jobs/import-v3-to-v4-via-ci.yml
  - cider-ci/jobs/meta.yml

jobs:
  test-container-deploy:
    include: [cider-ci/jobs/deploy-to-container.yml]
  prepare-cached-test-container:
    include: [cider-ci/jobs/prepare-cached-test-container.yml]
