#!/bin/sh
(
 echo "timestamp|duration|view|db"
 (
   #SELECT timestamp,completed_lines.request_id AS rid,duration,view,db,status,url 
   #WHERE processing_lines.controller = "Backend::AcknowledgeController";
   cat <<EOSQL
     SELECT timestamp,duration,view,db
       FROM completed_lines
       JOIN processing_lines
       ON completed_lines.request_id = processing_lines.request_id
       WHERE url LIKE '%hand_over%';
EOSQL
 ) | sqlite3 production.log.db \
   | awk '{print(substr($0,0,4)"-"substr($0,5,2)"-"substr($0,7,2)"-"substr($0,9,2)":"substr($0,11,2)":"substr($0,13)) }' \
   | sed 's/||/|-|/'
) > production.log.durations.csv

# the awk command fixes the date format
# the sed command replaces missing values with a '-'
