#You should *not* use this LDAP.yml
#Please read the Leihs LDAP guide

# configuration for the LDAP server
# host: where to reach the DRb server (used by application processes to contact the server)
# port: which port the server should listen on

production:
  host: ldapsrv.bfh.ch
  port: 636
  encryption: simple_tls
  base: dc=bfh,dc=ch
  log_file: log/ldap_server.log
  log_level: warn
  search_field: uid
  bind_dn: -----
  bind_pwd: -----

#test:
test:
  host: hostname
  port: port_number
  encryption: simple_tls
  base: dc=xyz,dc=abcc,dc=ch
  log_file: log/ldap_server.log
  log_level: warn
  search_field: userprincipalname
 

#dev:
development:
  host: ldapsrv.bfh.ch
  port: 636
  encryption: simple_tls
  base: dc=bfh,dc=ch
  log_file: log/ldap_server.log
  log_level: warn
  search_field: cn
  bind_dn: cn=$username,ou=srv-account,dc=bfh,dc=ch	
