# configuration for the LDAP server
# host: where to reach the DRb server (used by application processes to contact the server)
# port: which port the server should listen on

production:
  host: ldapsrv.bfh.ch
  port: 636
  encryption: simple_tls
  base: dc=bfh,dc=ch
  #Logging to extra file for LDAP module is not implemented (since at least Leihs 3.34.0)
  #LDAP errors will be written to STDERR, Debug messages to STDOUT
  #If you run Apache (production environment), check your Apache error log instead
  search_field: uid
  bind_dn: -----
  bind_pwd: -----

#test:
test:
  host: hostname
  port: port_number
  encryption: simple_tls
  base: dc=xyz,dc=abcc,dc=ch
  #Logging to extra file for LDAP module is not implemented (since at least Leihs 3.34.0)
  #LDAP errors will be written to STDERR, Debug messages to STDOUT
  #If you run Apache (production environment), check your Apache error log instead
  search_field: userprincipalname
 

#dev:
development:
  host: ldapsrv.bfh.ch
  port: 636
  encryption: simple_tls
  base: dc=bfh,dc=ch
  #Logging to extra file for LDAP module is not implemented (since at least Leihs 3.34.0)
  #LDAP errors will be written to STDERR, Debug messages to STDOUT
  #If you run Apache (production environment), check your Apache error log instead
  search_field: cn
  bind_dn: cn=$username,ou=srv-account,dc=bfh,dc=ch	
