# This file exists in order not to polute the culerity_steps.rb
# file as furnished/generated by upstream culerity.
#
# It contains additional web steps

# Use for debugging - i.e. verifying which page you're on
Then "show me the page" do
  puts "current URL: ", $browser.url
  puts
  puts "content of current page: ", $browser.html
end


