class AddBuildings < ActiveRecord::Migration

  def self.up    
    Building.create :code => "ZO", :name => "Andere Non-ZHDK Addresse"
    Building.create :code => "ZP", :name => "Heimadresse des Benutzern"
    Building.create :code => "ZZ", :name => "Nicht spezifizierte Adresse"
    Building.create :code => "SQ", :name => "Ausstellungsstrasse, 60"
    Building.create :code => "AU", :name => "Ausstellungsstrasse, 100"
    Building.create :code => "MC", :name => "Baslerstrasse, 30 (Mediacampus)"
    Building.create :code => "FH", :name => "Florhofgasse, 6"
    Building.create :code => "FB", :name => "Förrlibuckstrasse"
    Building.create :code => "FR", :name => "Freiestrasse, 56"
    Building.create :code => "GE", :name => "Gessnerallee, 11"
    Building.create :code => "HF", :name => "Hafnerstrasse, 27"
    Building.create :code => "HS", :name => "Hafnerstrasse, 31"
    Building.create :code => "HA", :name => "Herostrasse, 5"
    Building.create :code => "HB", :name => "Herostrasse, 10"
    Building.create :code => "HI", :name => "Hirschengraben, 46"
    Building.create :code => "KO", :name => "Limmatstrasse, 57"
    Building.create :code => "LH", :name => "Limmatstrasse, 47"
    Building.create :code => "LI", :name => "Limmatstrasse, 65"
    Building.create :code => "LS", :name => "Limmatstrasse, 45"
    Building.create :code => "PF", :name => "Pfingstweidstrasse, 6"
    Building.create :code => "SE", :name => "Seefeldstrasse, 225"
    Building.create :code => "FI", :name => "Sihlquai, 125"
    Building.create :code => "PI", :name => "Sihlquai, 131"
    Building.create :code => "TP", :name => "Technoparkstrasse, 1"
    Building.create :code => "TT", :name => "Tössertobelstrasse, 1"
    Building.create :code => "WA", :name => "Waldmannstrasse, 12"

    Building.create :code => "DG", :name => "Hafnerstrasse, 41"
    Building.create :code => "DI", :name => "Hafnerstrasse, 39"
    Building.create :code => "FOE", :name => "Förrlibuckstrasse, 62"
    Building.create :code => "P5", :name => "Hardturmstrasse, 11"
    Building.create :code => "MB", :name => "Höschgasse 3"
    Building.create :code => "VE", :name => "Höschgasse 4"
    Building.create :code => "MCA", :name => "Baslerstrasse, 30"
    Building.create :code => "FLG", :name => "Florhofgasse, 6"
    Building.create :code => "HI1", :name => "Hirschengraben, 1"
    Building.create :code => "HI20", :name => "Hirschengraben, 20"
    Building.create :code => "HI46", :name => "Hirschengraben, 46"
    Building.create :code => "FRS", :name => "Freiestrasse, 56"
    Building.create :code => "SFS", :name => "Seefeldstrasse, 225"
    Building.create :code => "GA9", :name => "Gessnerallee, 9"
    Building.create :code => "GA11", :name => "Gessnerallee, 11"
    Building.create :code => "GA13", :name => "Gessnerallee, 13"
    Building.create :code => "Z3", :name => "Militärstrasse, 47"
    Building.create :code => "FLS", :name => "Florastrasse, 52"
    Building.create :code => "MES", :name => "Merkurstrasse, 61"
    Building.create :code => "FLU", :name => "Flurstrasse, 85"
    Building.create :code => "ARS", :name => "Albisriederstr. 184B"
    Building.create :code => "TOE", :name => "Tösstobelstrasse, 1"
    Building.create :code => "RY82", :name => "Rychenberg, 82"
    Building.create :code => "RY94", :name => "Rychenberg, 94"
    Building.create :code => "RY96", :name => "Rychenberg, 96-100"
    Building.create :code => "IFS", :name => "Ifangstrasse, 2"
    Building.create :code => "BU", :name => "Schützenmattstrsse, 1B"
    Building.create :code => "KST", :name => "Kart-Stauffer-Strasse, 26"

  end
  
  def self.down
    Building.delete_all
  end
end
