jobs:

  borrow_scenarios:

    name: 'Borrow: Scenarios'

    description: |
      Run Borrow scenarios under MRI

    priority: -1

    run_when:
      branch name matches master or borrow:
        type: branch
        include_match: '^(.*master.*|[a-z]*/borrow_.*)$'
        exclude_match: '.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        load: 2
        max_trials: 3
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/borrow_scenarios.yml
