jobs:
  test-container-deploy:
    include: cider-ci/task-components/container-deploy.yml

    name: Test Deploy to Container

    run_when:
      integration tests were successful:
        type: job
        job_key: integration-tests
        states: [passed]


    context:

      task_defaults:
        environment_variables:
          LEIHS_ROOT_DIR: '{{CIDER_CI_WORKING_DIR}}'
          LEIHS_DEPLOY_DIR: '{{LEIHS_ROOT_DIR}}/deploy'

      tasks:

        ubuntu-2404:
          name: Ubuntu 24.04 (noble) LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2404.yml

        ubuntu-2204:
          name: Ubuntu 22.04 (jammy) LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2204.yml

        debian-bullseye:
          name: Debian 11 (bullseye)
          include: cider-ci/task-components/container-deploy/task-debian-11.yml

        debian-bookworm:
          name: Debian 12 (bookworm)
          include: cider-ci/task-components/container-deploy/task-debian-12.yml


