jobs:
  deploy-to-staging:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to zhdk-leihs-staging.ruby.zhdk.ch

    context:
      task_defaults:
        exclusive_global_resources:
          "zhdk-leihs-staging.ruby.zhdk.ch": true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "staging-hosts --limit zhdk-leihs-staging"
          STATUS_PAGE_URL: "https://ci.zhdk.ch/cider-ci/ui/workspace/trials/{{CIDER_CI_TRIAL_ID}}"
          LOCAL_CACHE_DIR: "/tmp/leihs-build-cache" # build cache same as for the tests

      tasks:
        deploy:
          include: cider-ci/task-components/zhdk-test-deploy.yml
