jobs:
  deploy-to-zhdk-leihs-demo:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to zhdk-leihs-demo.ruby.zhdk.ch
    run_when:
      nightly:
        type: cron
        value: '0 3 * * *'
        branch_include_match: ^(next|master)$
        rerun: true
      'on personal integration branch':
        type: branch
        include_match: ^[a-z]{2}_(next|master)$
        exclude_match: '^.*no-ci.*$'
    context:
      tasks:
        deploy:
          exclusive_global_resources:
            "zhdk-leihs-demo.ruby.zhdk.ch": true
          scripts:
            deploy:
              timeout: 30 Minutes
              body: |
                set -eux
                cd deploy
                export ANSIBLE_HOST_KEY_CHECKING=False
                ansible-playbook demo-deploy_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/demo-hosts
