jobs:
  test-container-deploy:
    include: cider-ci/task-components/container-deploy.yml

    name: Test Deploy to Container

    run_when:
      any branch matches:
        type: branch
        include_match: ^.+$
        exclude_match: ^.*(no-ci|hotspot).*$
#     integration tests were successful:
#       type: job
#       job_key: integration-tests
#       states: [passed]

    context:

      task_defaults:
        environment_variables:
          LEIHS_ROOT_DIR: '{{CIDER_CI_WORKING_DIR}}'
          LEIHS_DEPLOY_DIR: '{{LEIHS_ROOT_DIR}}/deploy'

      tasks:
        ubuntu-2204:
          name: Ubuntu 22.04 (jammy) LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2204.yml

        ubuntu-2004:
          name: Ubuntu 20.04 (focal) LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2004.yml

        debian-bullseye:
          name: Debian 11 (bullseye)
          include: cider-ci/task-components/container-deploy/task-debian-11.yml

        debian-bookworm:
          name: Debian 12 (bookworm)
          include: cider-ci/task-components/container-deploy/task-debian-12.yml


