jobs:
  deploy-to-ffzh-leihs-prod:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to FFZH production
    depends_on:
      "designated deploy branch":
        type: branch
        include_match: ^zhdk/deploy$
    context:
      tasks:
        deploy:
          exclusive_global_resources: { ffzh-leihs-prod.ruby.zhdk.ch: true }
          environment_variables:
            DEPLOY_TARGET_INVENTORY: "ffzh-prod-hosts"
          scripts:
            deploy:
              timeout: 1 Hour
              body: |
                set -euxo
                cd deploy
                export ANSIBLE_HOST_KEY_CHECKING=False
                bin/ansible-playbook deploy_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/${DEPLOY_TARGET_INVENTORY}
