jobs:

  good-to-merge:

    name: ⚑ Good To Merge

    description: |

      ⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡

      # VERSION 5 🆕✌️5️⃣ ###############################################

      ⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡

      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!

    # TMP: disable some jobs while working on v5
    depends_on: &GOOD_TO_MERGE_DEPENDENTS
      # deploy to demo was successful:
      #   type: job
      #   job_key: deploy-to-zhdk-leihs-demo
      #   states: [passed]
      # deploy to test was successful:
      #   type: job
      #   job_key: deploy-to-zhdk-leihs-test
      #   states: [passed]
      deploy to container was successful:
        type: job
        job_key: test-container-deploy
        states: [passed]
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]
      legacy submodule have passed:
        type: job
        job_key: good-to-merge
        submodule: ['legacy']
        states: [passed]
      # NEW IN v5
      admin submodule have passed:
        type: job
        job_key: good-to-merge
        submodule: ['admin']
        states: [passed]
      procure submodule have passed:
        type: job
        job_key: good-to-merge
        submodule: ['procure']
        states: [passed]

    run_when: *GOOD_TO_MERGE_DEPENDENTS

    priority: 999 # "empty" job = high priority
    
    context:
      task_defaults:
        max_trials: 1
      tasks:
        all relevant tests have passed:
          name: "All relevant tests have passed, thus good to merge"
          scripts:
            main:
              body: echo 'All relevant tests have passed' ; exit 0

        include:
          - path: cider-ci/context-components/merged-submodules-check.yml
            submodule: [legacy]
