jobs:

  manage_scenarios:

    name: 'Manage: Scenarios'

    description: |
      Run Manage scenarios under MRI

    priority: -1

    run_when:
      branch name matches master or manage:
        type: branch
        include_match: '^(.*master.*|[a-z]*/manage_.*)$'
        exclude_match: '.*no-ci.*$'

    context:

      task_defaults:
        max_trials: 3
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/manage_scenarios.yml
