jobs:
  meta:
    name: Meta
    description: |
      Various superordinate quality assurance tasks

    run_when:
      always:
        type: branch
        include_match: ^.*$
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      task_defaults:
        max_trials: 1
        traits:
          asdf: true
        git_options:
          submodules:
            include_match: ^.*$

      tasks:

        submodule-consistency:
          name: "identical submodules are on the same commit"
          include: cider-ci/task-components/submodule-consistency.yml

        ahead-of-master:
          name: "origin/master is ancestor of HEAD"
          include: cider-ci/task-components/ahead-of-master.yml

