jobs:

  procurement_scenarios:

    name: 'Procurement: Scenarios'

    description: |
      Run Procurement engine scenarios under MRI

    priority: -1

    run_when:
      branch name matches master or procurement:
        type: branch
        include_match: '^(.*master.*|[a-z]*/procurement_.*)$'
        exclude_match: '.*no-ci.*$'

    context:

      task_defaults:
        max_trials: 3
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/procurement_scenarios.yml
