jobs:

  procurement-scenarios:

    name: 'Procurement: Scenarios'

    description: |
      Run procurement engine scenarios under MRI

    priority: -1

    run-on:
    - type: branch
      include-match: '[a-z]*/procurement_.*$'
    - type: branch
      include-match: '[a-z]*/master.*$'

    context:
      task-defaults:
        max-auto-trials: 2

      _cider-ci_include:
        - cider-ci/shared/tests-context.yml
        - cider-ci/tasks/cucumber_procurement_scenarios.yml
